
/*
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    id LONG AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    alias VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    address VARCHAR(50),
    books LONG,
    rol VARCHAR(50) NOT NULL,
    FOREIGN KEY (creatoruser) REFERENCES BOOKS(creatoruser)
);

DROP TABLE IF EXISTS PRICEREDUCTION;
CREATE TABLE PRICEREDUCTION (
    id LONG AUTO_INCREMENT PRIMARY KEY,
    pricereduction VARCHAR(50) NOT NULL,
    startdate DATE NOT NULL,
    enddate DATE NOT NULL,
    books LONG NOT NULL,
);

DROP TABLE IF EXISTS SUPPLIER;
CREATE TABLE SUPPLIER (
    id LONG AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (50) NOT NULL,
    address VARCHAR(50) NOT NULL,
    books LONG NOT NULL,
    FOREIGN KEY (books) REFERENCES BOOKS(supplier)
);


DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS (
    id LONG AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (50) NOT NULL,
    itemcode LONG NOT NULL,
    description VARCHAR(50) NOT NULL,
    author VARCHAR(50) NOT NULL,
    gender VARCHAR(50) NOT NULL,
    price LONG NOT NULL,
    pricereduction LONG NOT NULL,
    state VARCHAR(50) NOT NULL,
    supplier LONG NOT NULL,
    creationdate DATE NOT NULL,
    creatoruser LONG NOT NULL,
    FOREIGN KEY (books) REFERENCES BOOKS(pricereduction)
);

*/